_wandb:
    value:
        cli_version: 0.21.4
        e:
            hwn9q8kvd9bbr9til4wdwv5cgny0alyb:
                codePath: CSE5ML_22843874_Assessment2_P1T1+3.ipynb
                codePathLocal: CSE5ML_22843874_Assessment2_P1T1+3.ipynb
                cpu_count: 10
                cpu_count_logical: 12
                disk:
                    /:
                        total: "510873563136"
                        used: "361865199616"
                email: tim.vos.nl@gmail.com
                executable: c:\Users\timvo\OneDrive\Documents\VSC Projects\CSE5ML\Assessment 2\TF_NN_MNIST\.venv\Scripts\python.exe
                git:
                    commit: 1a3a791e53ff8fd20abac389abdd852896cce3ac
                    remote: https://github.com/Sjakiesurfer1984/TF_NN_MNIST.git
                host: LaptopVanTim
                memory:
                    total: "16858472448"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\timvo\OneDrive\Documents\VSC Projects\CSE5ML\Assessment 2\TF_NN_MNIST\CSE5ML_22843874_Assessment2_P1T1+3.ipynb
                python: CPython 3.11.5
                root: c:\Users\timvo\OneDrive\Documents\VSC Projects\CSE5ML\Assessment 2\TF_NN_MNIST\wandb
                startedAt: "2025-09-14T07:37:10.499018Z"
                writerId: hwn9q8kvd9bbr9til4wdwv5cgny0alyb
        m:
            - "1": epoch/epoch
              "6":
                - 3
              "7": []
            - "2": epoch/*
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.11.5
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 7
                - 13
                - 16
                - 38
            "4": 3.11.5
            "5": 0.21.4
            "8":
                - 1
                - 3
            "12": 0.21.4
            "13": windows-amd64
batch_size:
    value: 64
epochs:
    value: 100
learning_rate:
    value: 0.001
optimiser:
    value: Adam
